import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'

export default function Home() {
  const [posts, setPosts] = useState([])

  useEffect(() => {
    getData()
  }, [])
  
  const getData = async () => {
    const link = await fetch(`https://api.adviceslip.com/advice`)
    const data = await link.json()
    setPosts(data.slip)
    console.log(data.slip)
  }
  
  const num = posts.id
  const advice = posts.advice

  return (
    <div>
      <Head>
        <title>Advice Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='dark-blue p-6 h-screen w-full flex justify-center items-center'>
        <div className='square w-1/3 h-60 rounded-lg flex flex-col items-center'>
          <h1 className='number-color text-sm text-center tracking-widest pt-8 pb-4'>
            ADVICE # {num}
          </h1>
          
          <p className='advice-color text-center text-2xl text-gray-600 px-3.5'>
            &apos;&apos;
            {advice}
            &apos;&apos;
          </p>
          
          <p className='advice-color text-3xl py-4'>&apos;&apos;</p>
          {/* <Image src="/pattern-divider-desktop.svg" alt='testing' width={20} height={20} /> */}
          {/* <form> */}
          <button className='circle w-12 h-12 my-14 absolute rounded-full text-center flex justify-center items-center'>
            <Image src="/icon-dice.svg" alt='testing' width={20} height={20} />
          </button>
          {/* </form> */}
        </div>
      </div>
    </div>
  )
}
